---
apiVersion: v1
kind: Secret
metadata:
  name: sundaland-mongodb-credentials
# FIXME
stringData:
  SUNDALAND_MONGODB_USER: "sundaland_user"
  SUNDALAND_MONGODB_PASSWORD: "sundaland_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: sundaland-pull-secret
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "dGllb3VsZS5jb3VsaWJhbHk6b2xRaG15aENXS05uSGQ1dDgzZk1EMjg2TVFwMU9tRTFad2suMDEuMHoxdTJtb3d5"
          }
      }
    }
type: kubernetes.io/dockerconfigjson
